/**
 * Tipagem referente ao tipo de integração para serviços de logística.
 */
export type ITipoIntegracao =
  | 'AmazonDBA'
  | 'B2WEntrega'
  | 'B2WO2O'
  | 'Cainiao'
  | 'Correios'
  | 'CorreiosLog'
  | 'CustomLogistic'
  | 'DafitiMilkrun'
  | 'Envvias'
  | 'Frenet'
  | 'FreteDescomplicado'
  | 'Intelipost'
  | 'Jadlog'
  | 'Jamef'
  | 'Kangu'
  | 'LogisticaShopee'
  | 'Loggi'
  | 'MagaluEntregas'
  | 'Mandae'
  | 'MelhorEnvio'
  | 'MercadoEnvios'
  | 'OlistFulfillment'
  | 'TotalExpress'
