/**
 * Valores de `type`.
 *
 * - `'BAD_REQUEST'`
 * - `'VALIDATION_ERROR'`
 * - `'MISSING_REQUIRED_FIELD_ERROR'`
 * - `'EMPTY_REQUEST_BODY'`
 * - `'INVALID_REQUEST_BODY'`
 * - `'INVALID_APIKEY_ERROR'`
 * - `'UNAUTHORIZED'`
 * - `'UNAUTHENTICATED'`
 * - `'FORBIDDEN'`
 * - `'RESOURCE_NOT_FOUND'`
 * - `'METHOD_NOT_ALLOWED'`
 * - `'TOO_MANY_REQUESTS'`
 * - `'UNKNOWN_ERROR'`
 * - `'SERVER_ERROR'`
 * - `'NOT_IMPLEMENTED'`
 */
export type IType =
  | 'BAD_REQUEST'
  | 'VALIDATION_ERROR'
  | 'MISSING_REQUIRED_FIELD_ERROR'
  | 'EMPTY_REQUEST_BODY'
  | 'INVALID_REQUEST_BODY'
  | 'INVALID_APIKEY_ERROR'
  | 'UNAUTHORIZED'
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'RESOURCE_NOT_FOUND'
  | 'METHOD_NOT_ALLOWED'
  | 'TOO_MANY_REQUESTS'
  | 'UNKNOWN_ERROR'
  | 'SERVER_ERROR'
  | 'NOT_IMPLEMENTED'
